### ISSUE TITLE
Spawn a task to recover blocks from HotShot

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/hotshot-query-service#217]
We should use a (multi-)producer (single-)consumer model, so that anywhere in the query service can enqueue a request to recover a block, but only one task is responsible for handling the requests. This task can thus deduplicate requests for the same block coming from different producers. The consumer task can delegate the actual handling of the requests to a pool of worker tasks if necessary, although this will be primarily I/O-bound, so this may not be necessary.

The consumer task will use [the HotShot API](https://github.com/EspressoSystems/HotShot/issues/1640) to do the actual fetching.

There should be an API for launching this task, which the application is expected to call at start-up. The query data and API modules will then need to be initialized with handles to the task (i.e. channel endpoints they can use to send requests and receive results).

Anywhere we discover a block is missing (ie when loading query data at startup, when receiving a leaf from HotShot with no corresponding block, or when looking up a block in response to a query) we should enqueue a request to fetch that block. The query data should subscribe to a stream of fetched blocks and update itself accordingly.

**Comment by sveitser** [comment]
Close https://github.com/EspressoSystems/espresso-sequencer/issues/680
