### ISSUE TITLE
Add Schnorr Signature streaming endpoint

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/hotshot-query-service#248]
Ref: https://github.com/EspressoSystems/HotShot/issues/2021

This issue adds endpoint for fetching the Schnorr signatures over new finalized hotshot state, this is expected to be invoked by the hotshot-state-prover service.

These signatures are stored on each replicas (who will optimistically send to CDN, thus available there as well), this signatures is periodically produced by the HotShot nodes, and when produced, it was sent along-side a leaf.

See more design details/descriptions here: https://www.notion.so/espressosys/Light-Client-Contract-a416ebbfa9f342d79fccbf90de9706ef?pvs=4#d38a8af153614615a2cde788ef32fad1

**Comment by mrain** [comment]
covered by https://github.com/EspressoSystems/espresso-sequencer/issues/801
