### ISSUE TITLE
Add endpoint for finalized block and justify QC

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/hotshot-query-service#259]
~We would like an end point serving not the latest block (which there's already API for that), but the latest finalized block -- a thin wrapper applying the HotShot finalization rule to the former existing API, for the convenience of downstream users who doesn't want to manually check finalization logic themselves.~

~cc @jbearer @philippecamacho~

---

_updated:_

> The latest block is already the finalized block. The query service only deals with finalized blocks.

This issues aims to add an endpoint to get the QC justification for the latest block proving its finalization status. (Currently HotShot does not provide those in the Decide event, we're just kind of expected to trust it.)

**Comment by jbearer** [comment]
The latest block is already the finalized block. The query service only deals with finalized blocks. I think the only thing we might need to add is an endpoint to get the two (or one, in HotStuff-2) QCs after the latest block, proving it's finalized. Currently HotShot does not provide those in the `Decide` event, we're just kind of expected to trust it.

**Comment by alxiong** [comment]
Thanks @jbearer  for the clarification! 
I have updated the issue description and removed from our roadmap for the light client board since we won't be using this.
